### ISSUE TITLE
Cache Support for Speed

### ISSUE THREAD

**Issue by scosman** [jidicula/clang-format-action#216]
Love this action, thanks for making it!

I'm seeing it consistently take 45s, almost all of which is fetching the docker image.

Thoughts on using the [cache](https://github.com/actions/cache) action to speed things up?

Example log: https://github.com/CriticalMoments/CriticalMoments/actions/runs/10893728646/job/30229199141

**Comment by echoix** [comment]
By showing the timestamps on your run, pulling the action+docker images takes between 3-5 seconds, depending on what you consider downloading. (Vs booting or finishing up the pull). A cache wouldn't be faster than pulling a docker container, especially one stored in ghcr.io.

So, the vast majority of the time (of the 42 secs total) seems taken by actually linting, so everything seems alright to me.

**Comment by scosman** [comment]
Oh! Sorry about the bad report.

The same project takes about 200ms locally for linting+reformatting with clang-format. I'm a bit confused on the 200x slowdown, but will investigate.

**Comment by echoix** [comment]
This action has or had a problem where it called a docker container for each individual file, instead of passing multiple files at once. So the runtime is way more than it should be.

See #147 for an analysis I did for a my project where this action took 22 minutes, and another clang-format action, wrapped differently, ended up taking 30 seconds.
