### ISSUE TITLE
Configuration file(s) do(es) not support Objective-C: /github/workspace/./.clang-format, /github/workspace/.clang-format

### ISSUE THREAD

**Issue by lovettchris** [jidicula/clang-format-action#40]
I tried to use clang-format-action in this [repo](https://github.com/microsoft/AirSim/pull/3692), and I'm not getting any clang-formatting errors reported in the run, but the check still fails?  Can you tell why?  I'm testing this in this [branch](https://github.com/microsoft/AirSim/pull/3692).

Here's the full log output of the `jidicula/clang-format-action@v3.3.0` run:
[log.txt](https://github.com/jidicula/clang-format-action/files/6475919/log.txt)

See also my [github workflow ](https://github.com/microsoft/AirSim/pull/3692/files#diff-4fc2638f81c0ac4a14a555e3e18a212d3b05345df4f269688f2bb090d5a8b3bd) which I mostly copy/pasted from your sample...

**Comment by jidicula** [comment]
Hmm, a quick search of the error output indicates it could be an issue with `clang-format` itself where it might [mistake some C++ syntax for Objective-C](https://lists.llvm.org/pipermail/llvm-bugs/2018-May/064824.html)... There's also a similar issue described in angular/clang-format#58, but where it's mistaking some ts/js files for C++ because fallback wasn't specified.

I take it you don't actually have any Objective-C files in your repo that might be triggering this failure?

There are 2 things I want to try that might give us some more information:

1. Running with a modified form of my [`entrypoint.sh`](https://github.com/jidicula/clang-format-action/blob/main/entrypoint.sh) script that has an additional `echo` command to say which file triggered the failure (change is visible in #41).
2. Passing `clang-format` a fallback style so it explicitly tries to recognize files as C++

For 1: Can you modify [this line](https://github.com/microsoft/AirSim/blob/f7ba9b34b726820da07a95cfabf1f08570082768/.github/workflows/clang_format.yml#L10) of your workflow file to:

```
uses: jidicula/clang-format-action@ji/issue-40
```

For 2: In a separate commit (so it triggers a separate run), can you try adding a [fallback style](https://github.com/jidicula/clang-format-action#inputs) input to your GH Actions workflow config? Doesn't matter which one (maybe Google or Mozilla might be best?), but let's see if it changes the error output.

---

Sorry I don't have an immediate fix for this and that we have to take a bit of an indirect route to hopefully resolve this.

If we're still unable to solve this, I can try adding clang-format-12 support via #38 this weekend and we can see if the issue is resolved there... in the meantime, you could also try using versions 8, 9, and 10 to see if they fail similarly.

**Comment by lovettchris** [comment]
Thanks man!  That "echo" line is super helpful in debugging this, you should keep that!  Turn out it is a clang-format bug triggered by some very funky C++ syntax on line [717 of mavlink_helpers.h](https://github.com/microsoft/AirSim/blob/master/MavLinkCom/mavlink/mavlink_helpers.h#L717) so I can probably rework that to avoid this bug...

**Comment by lovettchris** [comment]
Golden, I just disabled clang-formatting for the file as a workaround for now, so I'm closing this issue, thanks again.

![image](https://user-images.githubusercontent.com/18707114/118216849-1e4db500-b429-11eb-9663-add91827c2d6.png)

**Comment by jidicula** [comment]
My pleasure @lovettchris! I've just created a new release including this change - you can update your workflows to point to `jidicula/clang-format-action@v3.4.0`.

**Comment by clovett** [comment]
awesome, I'll switch to that version, thanks.
