### ISSUE TITLE
Feature suggestion: add review comments suggesting clang-format changes

### ISSUE THREAD

**Issue by MaximeHouis** [jidicula/clang-format-action#45]
It would be very neat if the action would, optionally obviously, suggest changes on a pull request if there are any format errors.  
Or, if it isn't possible or too hard to implement, adding simple comments on the PR would still be cool.

Thanks for this action, I find it very useful :smile:

**Comment by jidicula** [comment]
That's certainly an interesting suggestion, but I think I'll have to decline – intuitively it seems out of scope for me to add it here. If there are format errors, my `entrypoint.sh` script will echo the offending filenames as well as the output of `clang-format`, so you would be able to see those outputs in the GitHub Actions run log. The fix would generally be to run clang-format locally on your file and commit-push to GitHub. (I assume syntax errors wouldn't be an issue if you have a local compilation step, or at least a compilation step in CI.)

If this Action were for a linter that flags code smells rather than a format checker, I'd be more in favour of including PR comment functionality. With linting there are many degrees of correctness between a flagged snippet and a refactor of the snippet that's not flagged – to my knowledge, most/all static linters check for the presence of antipatterns, rather than checking that the code conforms to a known-correct pattern. It would be helpful to see those antipatterns highlighted explicitly in a PR check, and even with options for refactoring it, or a link to an explanation of why those are deemed antipatterns. I've used [Semgrep](https://semgrep.dev) for this in some work projects and found it to be useful.

In contrast to linting, a formatting check has a (hopefully deterministic, but there are certainly [formatters](https://github.com/google/yapf) that aren't) known-correct state and it compares the code to that state. Because there's a single known-correct state, I wouldn't find PR comments to be particularly informative – as I mentioned above, my first instinct would be to just run `clang-format` locally on the offending files (or just on the whole project if I'm feeling particularly lazy) and commit the formatting changes. I typically have a format-on-save setting enabled in my editor as well, so I don't diverge from my projects' formatting rules. If this isn't possible, I would recommend looking into [pre-commit](https://pre-commit.com), so at least you have some degree of automation that's not too intrusive if format-on-save takes too long.

I'm sorry that I have to reject your feature request, but I hope this explains my reasoning for saying no.

**Comment by MaximeHouis** [comment]
Understandable, thank you for the insights!

It makes total sense, cheers :)
