### ISSUE TITLE
Decouple from specific distros

### ISSUE THREAD

**Issue by Krzmbrzl** [jidicula/clang-format-action#63]
In the light of #62 I was wondering if it might generally be a better idea to use Dockerfiles building clang then and there (e.g. https://hub.docker.com/r/silkeh/clang) instead of relying on specific Ubuntu/Debian packages providing specific versions to be used. That way the available clang-format versions would be decoupled from the lifecycle of any distros.

The way I parse the process of the linked Dockerfiles is that they actually only download the binaries as well instead of rebuilding from source every time, which should be a good way to minimize the overhead that would otherwise occur

**Comment by jidicula** [comment]
The apt install on every workflow run is a solid issue that I've been wanting to improve on for a while (see also #33). The only caveat I see to your proposed change is working around how GitHub Actions accepts args - as I recall, it's not possible to pass Actions workflow inputs to the Docker image declaration, only to its entrypoint (which is why I put the `clang-format` installation inside the shell script rather than a step in the Docker build). I may be wrong, though - I'll have to look into this further, and let me know if you know a way to do that.

**Comment by jidicula** [comment]
Possibly some workarounds in here https://github.community/t/feature-request-build-args-support-in-docker-container-actions/16846

**Comment by Krzmbrzl** [comment]
I guess you could hack around this restriction by running a shell script inside the action, that reads in the arg and then uses some Bash-utility to write the corresponding Dockerfile to disk and then executing that dynamically created Dockerfile. Alternatively, the script could dynamically decide which of a set of pre-crafted Dockerfiles to choose from.

So for instance, if you consider having a repo such as https://github.com/silkeh/docker-clang/ it should be really easy to select the appropriate Dockerfile dynamically :thinking:

**Comment by jidicula** [comment]
Oh that's an interesting approach, I like it much better than the nested Docker instances.
